### ISSUE TITLE
WeakMultiLabels or MajorityVoter function not working as expected

### ISSUE THREAD

**Issue by BiswajitGhoshal** [recognai/rubrix#2085]
**Describe the bug**
WeakMultiLabels("test_weak_label") is apparently reading the dataset from Argilla running on my machine, but MajorityVoter function is not getting any dataset.  As a result, the classifier program is not getting formed.

**To Reproduce**
1. I used the dataset as in attached excel-file: weak_test_classifier.
2. Create a json-load file out of the data in the excel-file using: create_load_file.py.
3. Upload the json-load file into a argilla dataset, named: test_weak_label, using: create_rubrix_dataset_new.py.
4. Define the rules as given in the rules.jpg screenshot.
5. Run the classifier-program to create a classification-model using: TestClassifier.py.
6. The output of step-4 is as follows:
```bash
(10, 6, 3)
weak_labels type:  <class 'argilla.labeling.text_classification.weak_labels.WeakMultiLabels'> label_model type:  <class 'argilla.labeling.text_classification.label_models.MajorityVoter'>
Empty DataFrame
Columns: []
Index: []
Traceback (most recent call last):
  File "TestClassifier.py", line 50, in <module>
    train_df["label"] = train_df.prediction.map(multi_label_binarizer)
  File "C:\Anaconda3\envs\elasticsearch\lib\site-packages\pandas\core\generic.py", line 5907, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'prediction'
```

**Expected behavior**
I was expecting to develop a classifier model, and output should have been the metrics of the model, as described in your sample ResearchTopics classifier code.

**Screenshots**
Program output has been already shared.  Attached please find the data-file and 3 python scripts.

**Environment (please complete the following information):**
 - OS [e.g. iOS]: Windows
 - Browser [e.g. chrome, safari]: Chrome
 - Argilla Version [e.g. 1.0.0]: 1.0.1
 - ElasticSearch Version [e.g. 7.10.2]: 8.4.3
 - Docker Image (optional) [e.g. argilla:v1.0.0]: not applicable

**Additional context**
Please let me know where I'm going wrong or if any other information is required.
[weak_test_classifier.xlsx](https://github.com/argilla-io/argilla/files/10285123/weak_test_classifier.xlsx)
[files.zip](https://github.com/argilla-io/argilla/files/10285147/files.zip)

**Comment by davidberenstein1957** [comment]
Hi @BiswajitGhoshal, happy new year and sorry for the late response. The holidays were busy. I will take a look this week.

**Comment by davidberenstein1957** [comment]
Hi @BiswajitGhoshal, your error was caused by the `MajorityVoter.predict()` default parameters. *edit* because you records are all annotated and `include_annotated_records` is set to False, there is an empty `DataFrame` being  returned by the MajorityVoter.

```
Applies the label model.

Args:
    include_annotated_records: Whether to include annotated records.
    include_abstentions: Whether to include records in the output, for which the label model abstained.
    prediction_agent: String used for the prediction_agent in the returned records. tie_break_policy: Policy to break ties (IGNORED FOR MULTI-LABEL!). You can choose among two policies:

- `abstain`: Do not provide any prediction
- `random`: randomly choose among tied option using deterministic hash
        The last policy can introduce quite a bit of noise, especially when the tie is among many labels, as is the case when all the labeling functions (rules) abstained.

Returns:
    A dataset of records that include the predictions of the label model.
```
