### ISSUE TITLE
Error when logging large text

### ISSUE THREAD

**Issue by madrueno** [recognai/rubrix#2261]
**Describe the bug**
When I try to log a large text, the following error occurs:
```bash
argilla.client.sdk.commons.errors.GenericApiError: Argilla server returned an error with http status: 500
Error details: [{'code': 'argilla.api.errors::GenericServerError', 'params': {'type': 'elasticsearch.helpers.BulkIndexError', 'message': '1 document(s) failed to index.'}}]
```

**To Reproduce**
Execute the following Python script:
```python

import spacy
import argilla as rg

if __name__ == '__main__':
    nlp = spacy.load('en_core_web_sm')

    text = 'hello ' * 10000

    record = rg.TokenClassificationRecord(
        text=text,
        tokens=[token.text for token in nlp(text)],
        prediction=[('label1', 0, len(text), 1)]    
    )

    rg.log(record, 'test')
```

**Expected behavior**
The previous record is uploaded.

**Environment**
Python client: `argilla==1.2.1`
Server: The following Docker Compose
```yaml
version: "3.9"

services:
  argilla:
    image: argilla/argilla-server:latest
    restart: unless-stopped
    ports:
      - "6900:6900"
    environment:
      ARGILLA_ELASTICSEARCH: http://elasticsearch:9200
    networks:
      - argilla
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.3
    environment:
      - node.name=elasticsearch
      - cluster.name=es-argilla-local
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - cluster.routing.allocation.disk.threshold_enabled=false
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - argilla
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticdata:/usr/share/elasticsearch/data/
  kibana:
    image: docker.elastic.co/kibana/kibana:8.5.3
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
    networks:
      - argilla
networks:
  argilla:
    driver: bridge
volumes:
  elasticdata:
```
