### ISSUE TITLE
[UI] Misalignment in prediction underline at line wrap

### ISSUE THREAD

**Issue by tomaarsen** [recognai/rubrix#2282]
Hello!

## Issue Overview
* I've noted a misalignment in the light & thick and dark & thin prediction (underline) borders when the line wraps:

## Relevant screenshots
![image](https://user-images.githubusercontent.com/37621491/216580549-dec83005-83f7-4856-84c0-f2ee14b8d756.png)
![image](https://user-images.githubusercontent.com/37621491/216580867-cbea19ff-61bf-495d-b1f7-bf4c15b90d8f.png)

## Reproduction
Browse to https://argilla-live-demo.hf.space/datasets/team/gutenberg_spacy-ner-monitoring?query=e30&sort=W10&viewMode=explore&pagination=eyJzaXplIjoxMCwicGFnZSI6MX0 and observe the third record. Perhaps some messing with browser zoom levels is required, although for me it works with the default zoom on Firefox.

## Details
On the prediction side of the HTML, each word is wrapped in a span like so:
```html
<span data-v-45fa2b16="" class="highlight__content">
    the 
    ::after
</span>
```
Such that the span is affected by the following CSS rule for the light & thick prediction line:
```css
.color_15.prediction[data-v-9bc3bafe] .highlight__content {
	padding-bottom: 3px;
	border-bottom: 5px solid #c2efff;
	position: relative;
}
```
This one is always correctly placed.

However, because the designs asks for a secondary border, a common trick was used to place the second border: an `::after` tag (https://css-tricks.com/snippets/css/multiple-borders/). This tag is affected by this CSS rule to apply the dark & thin prediction line:
```css
.color_15.prediction[data-v-9bc3bafe] .highlight__content::after {
	content: "";
	border-top: 1px solid #0091c2;
	position: absolute;
	top: 26px;
	left: 0;
	right: 0;
}
```
However, unlike the `span`, this `::after` tag does *not* ignore the whitespace which is present in the text: `the `. This directly results in the bug.

## Proposed solution
I propose the following changes:
1. Remove the `::after` from the prediction. Furthermore, the corresponding CSS rule should be removed too. This removes the sometimes misaligned underline.
2. Expand the span CSS rule responsible for adding the light & thick underline with:
    ```css
    box-shadow: 0px 1px 0px #0091c2
    ```
    Where 0px is the x-offset, 1px is the y-offset, 0px is the blur radius and #0091c2 should be replaced with the correct dark color that was previously used in the `::after` css rule.

This simple alternative approach for providing multiple (underline) borders should solve this problem easily.

## After applying these changes
![image](https://user-images.githubusercontent.com/37621491/216584746-bfd2ef44-2d3f-469d-b4b5-9d8db96c8bb8.png)
![image](https://user-images.githubusercontent.com/37621491/216584865-f2708354-ad15-4597-9e92-d0d870995118.png)

- Tom Aarsen
