### ISSUE TITLE
`uppercase`/`lowercase` naming for workspaces does not align `users.yml` vs `API`

### ISSUE THREAD

**Issue by kdutia** [recognai/rubrix#2388]
**Describe the bug**
I've set up Argilla using docker-compose and added a `.users.yaml` which I know is being read, as I can log in with any of the users specified in the yaml.

When I load a dataset into a user's personal space via the Python library it works fine, but when I specify a shared workspace either using `rg.init(workspace="GST")` or `rg.set_workspace("GST")`, data logging fails with the following error:

```
Cannot log data in dataset 'demo_unlabelled'
Error: GenericApiError
Details: Argilla server returned an error with http status: 500
Error details: [{'code': 'argilla.api.errors::GenericServerError', 'params': {'type': 'argilla.server.daos.backend.base.IndexNotFoundError', 'message': "NotFoundError(404, 'index_not_found_exception', 'no such index [ar.dataset.GST.demo_unlabelled]', ar.dataset.GST.demo_unlabelled, index_or_alias)"}}]
```

**To Reproduce**
Code to reproduce:
```py
# V1 failure
rg.init(workspace="GST", api_key=os.environ["ARGILLA_API_KEY"])
_records = create_records() # Implementation unimportant for this bug report
rg.log(
    records, 
    name="demo_unlabelled", 
    metadata=dataset_metadata,
)

# V2 failure
_records = create_records() # Implementation unimportant for this bug report
rg.set_workspace("GST")
rg.log(
    records, 
    name="demo_unlabelled", 
    metadata=dataset_metadata,
)
```

**Expected behavior**
The data loads.

**Screenshots**

**Environment (please complete the following information):**
Docker-compose yaml fetched from the latest docs. OSX 12.2.1.

``` yaml
version: "3.9"

services:

  argilla:
    image: argilla/argilla-server:latest
    restart: unless-stopped
    ports:
      - "6900:6900"
    environment:
      ARGILLA_ELASTICSEARCH: http://elasticsearch:9200
      # Opt-out for telemetry https://docs.argilla.io/en/latest/reference/telemetry.html
      ARGILLA_ENABLE_TELEMETRY: 0

      # Set user configuration https://docs.argilla.io/en/latest/getting_started/installation/configurations/user_management.html
      ARGILLA_LOCAL_AUTH_USERS_DB_FILE: /config/.users.yaml
    volumes: 
      - $PWD/src/argilla/.users.yaml:/config/.users.yaml
    networks:
      - argilla

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.3
    environment:
      - node.name=elasticsearch
      - cluster.name=es-argilla-local
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - cluster.routing.allocation.disk.threshold_enabled=false
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - argilla
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticdata:/usr/share/elasticsearch/data/
  kibana:
    image: docker.elastic.co/kibana/kibana:8.5.3
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
    networks:
      - argilla
networks:
  argilla:
    driver: bridge
volumes:
  elasticdata:
```

**Additional context**
