### ISSUE TITLE
[BUG] Argilla not working behind proxy

### ISSUE THREAD

**Issue by gabrielmbmb** [recognai/rubrix#3542]
**Describe the bug**
Argilla is not working properly when working behind a proxy. Given the following `docker-compose.yaml`:

```yaml
version: '3.8'

services:
  argilla:
    image: argilla/argilla-quickstart:v1.13.3
    environment:
      ARGILLA_BASE_URL: /argilla
      LOAD_DATASETS: none
    ports:
      - 6900:6900

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
 ```

and the following `nginx.conf`:

```
http {
  server {
      listen 80;

      server_name your_server_name_or_ip;

      location /argilla/ {
          proxy_pass http://argilla:6900/;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
      }
  }
}
```

The Argilla server is returning `{"detail":"Not Found"}` when accessing `localhost/argilla` from a web browser and to connect using the Python client the following code is required:

```python
import argilla as rg

rg.init(api_url="http://localhost/argilla/argilla", api_key="owner.apikey")
```
Adding the extra `/argilla` shouldn't be required.

**Expected behavior**

Argilla UI loads when configured behind a proxy and to connect to the server from the Python client it's not required adding extra URL paths.

**Environment:**
 - Argilla Version [e.g. 1.0.0]: 1.13.3
 - ElasticSearch Version [e.g. 7.10.2]:
 - Docker Image (optional) [e.g. argilla:v1.0.0]: argilla/argilla-quickstart:v1.13.3

**Additional context**
This issue was originally reported by Chris Ballard in the [Slack community channel](https://rubrixworkspace.slack.com/archives/C02G2TZFG3V/p1691407463360219).
