### ISSUE TITLE
[CI] Disable telemetry events on CI for integration tests

### ISSUE THREAD

**Issue by jfcalvo** [recognai/rubrix#3921]
We should set `ARGILLA_ENABLE_TELEMETRY` environment variable to `0` in order to be sure that we are not sending telemetry events inside GitHub actions running our integration test suite.

**Comment by alvarobartt** [comment]
Also maybe internally (in the team) we should all probably disable it to avoid contaminating the metrics too?

**Comment by dvsrepo** [comment]
Yes, we need both

**Comment by gabrielmbmb** [comment]
@jfcalvo I had pending creating a PR to add https://github.com/MobileDynasty/pytest-env as a test dependency. This way we could have this section in the `pyproject.toml` to automatically set environment variables values when running the tests:

```toml
[tool.pytest.ini_options]
log_format = "%(asctime)s %(name)s %(levelname)s %(message)s"
log_date_format = "%Y-%m-%d %H:%M:%S"
log_cli = "True"
testpaths = ["tests"]
env = [
    "ARGILLA_DATABASE_URL=sqlite+aiosqlite:///{HOME}/.argilla/test.db",
    "ARGILLA_ENABLE_TELEMETRY=0"
]
```
