### ISSUE TITLE
[BUG] `push_to_huggingface` sometimes include tags in resulting `argilla.yml` file

### ISSUE THREAD

**Issue by gabrielmbmb** [recognai/rubrix#4089]
**Describe the bug**
In some environments, when using `FeedbackDataset.push_to_argilla`, it generates an `argilla.yaml` file that includes tags that later prevents the `from_huggingface` function to work correctly as they yaml cannot be loaded back because of the tags.

```yaml
allow_extra_metadata: true
fields:
- name: prompt
  required: true
  title: Prompt
  type: !!python/object/apply:argilla.client.feedback.schemas.enums.FieldTypes # <-- tag here
  - text
  use_markdown: true
```

**Expected behavior**
No matter what environment is used, the `push_to_argilla` should generate the yaml without tags.

**Environment:**
 - Argilla Version [e.g. 1.0.0]: 1.18.0
 - ElasticSearch Version [e.g. 7.10.2]: not relevant
 - Docker Image (optional) [e.g. argilla:v1.0.0]: not relevant
