### ISSUE TITLE
Issue SSL Certificate for Rubrix

### ISSUE THREAD

**Issue by davidkartchner** [recognai/rubrix#764]
Background:  
I'm running Rubrix on a server to be accessed by multiple annotators in my organization.  I would like to forward it so that all users can log in by accessing the right internal website when connected to VPN.   I am running Rubrix via docker-compose.

Problem: 
I need to serve Rubrix with a SSL certificate to ensure a security of users.

Is currently a way to do this?  I'm not seeing anything in the documentation.

Thanks!

**Comment by dvsrepo** [comment]
Hi @davidkartchner , thanks for reaching out and using Rubrix. @frascuchon will be able to answer this. In the meantime, just wanted to make sure you've seen the User and Workspace management feature included in the 0.7.0 release: https://rubrix.readthedocs.io/en/stable/getting_started/user-management.html

**Comment by frascuchon** [comment]
Hi @davidkartchner , thanks for using Rubrix.

You have several choice for that, even more if you're using the docker installation. 

I recommend you to use a "TLS Termination Proxy" instead of manage certificates yourself. For that case, you can configure an nginx proxy server with Let's Encript and setup your Rubrix instance behind the proxy. [This guide](https://pentacent.medium.com/nginx-and-lets-encrypt-with-docker-in-less-than-5-minutes-b4b8a60d3a71) explains quite well how to do that.

If you have already generated certificates or you want to use  your custom ones, you can use the `GUNICORN_CMD_ARGS` env var passing the route to mounted certificates:

```yml
   environment:
      GUNICORN_CMD_ARGS: "--keyfile=/secrets/key.pem --certfile=/secrets/cert.pem"
      ...
   volumes:
      - host/path/to/your/key.pem:/secrets/key.pem
      - host/path/to/your/cert.pem:/secrets/cert.pem
```

or again you can configure an nginx container with your certificates and keep intact you Rubrix configuration.

Also you could deploy your Rubrix instance in a cloud provider and use TLS Termination for the load balancers
